### ISSUE TITLE
Bug report from HA 2024.

### ISSUE THREAD

**Issue by downtownsj1973** [dcmeglio/homeassistant-petsafe#13] opened 2024-06-06 21:57 UTC
Showed up after recent HA upgrade"

Running HA on:

Operating System: CentOS Stream 9
     CPE OS Name: cpe:/o:centos:centos:9
          Kernel: Linux 5.14.0-437.el9.x86_64
    Architecture: x86-64
 Hardware Vendor: Intel_R_ Client Systems
  Hardware Model: NUC10i7FNH

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 5:49:51 PM (746 occurrences)
Last logged: 5:53:19 PM

`Detected` blocking call to open inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 269: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/gzip.py, line 192: fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues Traceback (most recent call last): File "/srv/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 828, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 941, in async_update_ha_state await self.async_device_update() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1289, in async_device_update await self.async_update() File "/home/homeassistant/.homeassistant/custom_components/petsafe/SwitchEntities.py", line 133, in async_update return await super().async_update() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 529, in async_update await self.coordinator.async_request_refresh() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 262, in async_request_refresh await self._debounced_refresh.async_call() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/debounce.py", line 111, in async_call if task := self.hass.async_run_hass_job( File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 939, in async_run_hass_job return self._async_add_hass_job(hassjob, *args, background=background) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 748, in _async_add_hass_job task = create_eager_task( File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 288, in async_refresh await self._async_refresh(log_failures=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/home/homeassistant/.homeassistant/custom_components/petsafe/__init__.py", line 269, in _async_update_data self._feeders = await self.api.get_feeders()
Detected blocking call to open inside the event loop by custom integration 'petsafe' at custom_components/petsafe/SensorEntities.py, line 232: feeding = await feeder.get_last_feeding() (offender: /usr/local/lib/python3.12/gzip.py, line 192: fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues Traceback (most recent call last): File "/srv/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 828, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 941, in async_update_ha_state await self.async_device_update() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1289, in async_device_update await self.async_update() File "/home/homeassistant/.homeassistant/custom_components/petsafe/SensorEntities.py", line 232, in async_update feeding = await feeder.get_last_feeding()
Detected blocking call to open inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 270: self._litterboxes = await self.api.get_litterboxes() (offender: /usr/local/lib/python3.12/gzip.py, line 192: fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues Traceback (most recent call last): File "/srv/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 288, in async_refresh await self._async_refresh(log_failures=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/home/homeassistant/.homeassistant/custom_components/petsafe/__init__.py", line 270, in _async_update_data self._litterboxes = await self.api.get_litterboxes()`

**Comment by dcmeglio** [comment] 2024-07-31 00:33
Duplicate of #14

**Closed by dcmeglio** 2024-07-31 00:33 UTC
