### ISSUE TITLE
Constant Authentication expired for …

### ISSUE THREAD

**Issue by ichrispod** [dcmeglio/homeassistant-petsafe#17] opened 2024-09-06 02:04 UTC
About every 2-3 days I need to re-authorize my account. Is this normal?
![IMG_4654](https://github.com/user-attachments/assets/9c25d991-b3f4-44b8-8854-7da3a2da178a)
![IMG_4655](https://github.com/user-attachments/assets/e013b8ca-93c0-405b-a77c-4b1bd6e6ffb4)

**Comment by aristeu** [comment] 2024-09-06 13:09
I have the same issue. Interested to know.

**Comment by dcmeglio** [comment] 2024-09-07 13:25
Duplicate of #12. No this is not expected, I can reproduce it but haven't tracked down the root cause. The tricky part is when I think I may have fixed it I have to wait several days to see if I really did.

**Closed by dcmeglio** 2024-09-07 13:25 UTC
